---
language: python
python: "2.7"

sudo: required
dist: trusty
services:
  - docker

env:
  - distribution: centos
    version: 7
  - distribution: centos
    version: 6
  - distribution: ubuntu
    version: 16.04
  - distribution: ubuntu
    version: 14.04

before_install:
  - 'sudo docker run -it --name=test_dummy --privileged --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:rw cyverse/ansible-test:latest-${distribution}-${version} bash'

script:
  # 1. Syntax check
  - "sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --syntax-check"

  # 2. Run playbook to execute role
  - "sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local"

  # 3. Idempotence test (run playbook again to confirm nothing changes)
  - >
    sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)


notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications
    on_success: always
    on_failure: never
