---

- import_tasks: get-cert-cn.yml
  when: 'TLS_COMMON_NAME is undefined'

- import_tasks: register-file-paths.yml

- name: Certificate files copied to target
  tags: [certs-copied]
  copy:
    src: '{{ item.src_path }}'
    dest: '{{ item.dest_path }}'
  with_items:
    - src_path: '{{ TLS_BYO_PRIVKEY_SRC }}'
      dest_path: '{{ TLS_PRIVKEY_PATH }}'
    - src_path: '{{ TLS_BYO_CERT_SRC }}'
      dest_path: '{{ TLS_CERT_PATH }}'
    - src_path: '{{ TLS_BYO_CACHAIN_SRC }}'
      dest_path: '{{ TLS_CACHAIN_PATH }}'

- name: Full certificate chain created
  shell: 'cat {{ TLS_CERT_PATH }} {{ TLS_CACHAIN_PATH }} > {{ TLS_FULLCHAIN_PATH }}'
